# Generated by Django 4.2.8 on 2024-02-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='invite_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
